/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the ACL that you want to create. 
type AclPostRequest struct {

	// Description of the ACL.
	Description string `json:"description,omitempty"`

	// Enables or disables the ACL. Set to <code>true</code> by default. Set this to <code>false</code> to disable the ACL.
	EnabledFlag bool `json:"enabledFlag,omitempty"`

	// The three-part name of the ACL (/Compute-identity_domain/user/object).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive. When you specify the object name, ensure that an object of the same type and with the same name doesn't already exist. If such an object already exists, another object of the same type and with the same name won't be created and the existing object won't be updated.
	Name string `json:"name"`

	// Strings that you can use to tag the ACL.
	Tags []string `json:"tags,omitempty"`
}
