/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the image list that you want to update. 
type ImageListPutRequest struct {

	// <p>The image list entry to be used, by default, when launching instances using this image list. If you don't specify this value, it is set to 1.
	Default_ int32 `json:"default,omitempty"`

	// <p>A description of this image list.
	Description string `json:"description"`

	// The three-part name of the object in the following format: <code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>.
	Name string `json:"name"`
}
