/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ImageListResponse struct {

	// <p>The image list entry to be used, by default, when launching instances using this image list. If you don't specify this value, it is set to 1.
	Default_ int32 `json:"default,omitempty"`

	// <p>A description of this image list.
	Description string `json:"description,omitempty"`

	// Each machine image in an image list is identified by an image list entry.
	Entries []ImageListEntryResponse `json:"entries,omitempty"`

	// The three-part name of the image list.
	Name string `json:"name,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`
}
