/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the IP address prefix set that you want to update. 
type IpAddressPrefixSetPutRequest struct {

	// Description of the IP address prefix set.
	Description string `json:"description,omitempty"`

	// List of CIDR IPv4 prefixes assigned in the virtual network.
	IpAddressPrefixes []string `json:"ipAddressPrefixes,omitempty"`

	// The three-part name of the IP address prefix set (/Compute-identity_domain/user/object).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive. When you specify the object name, ensure that an object of the same type and with the same name doesn't already exist. If such an object already exists, another object of the same type and with the same name won't be created and the existing object won't be updated.
	Name string `json:"name"`

	// Strings that you can use to tag the IP address prefix set.
	Tags []string `json:"tags,omitempty"`
}
