/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the IP address association that you want to create. 
type IpAddressAssociationPostRequest struct {

	// Description of the IP address association.
	Description string `json:"description,omitempty"`

	// The three-part name of the NAT IP address reservation (/Compute-identity_domain/user/object).
	IpAddressReservation string `json:"ipAddressReservation,omitempty"`

	// The three-part name of the Ip address association (/Compute-identity_domain/user/object).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive. When you specify the object name, ensure that an object of the same type and with the same name doesn't already exist. If such an object already exists, another object of the same type and with the same name won't be created and the existing object won't be updated.
	Name string `json:"name"`

	// Description of the IP address association.
	Tags []string `json:"tags,omitempty"`

	// Multipart name of the virtual NIC that you want to associate with the NAT IP reservation.
	Vnic string `json:"vnic,omitempty"`
}
