/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type IpNetworkResponse struct {

	// Description of the object.
	Description string `json:"description,omitempty"`

	// CIDR IPv4 prefix associated with this IP network.
	IpAddressPrefix string `json:"ipAddressPrefix,omitempty"`

	// Name of the IP network exchange associated with this IP network.
	IpNetworkExchange string `json:"ipNetworkExchange,omitempty"`

	// The three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) of the IP network.
	Name string `json:"name,omitempty"`

	// Tags associated with the object.
	Tags []string `json:"tags,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`
}
