/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type LaunchPlanResponse struct {

	// <p>A list of instances.<p>Each instance is defined using the instance attributes.
	Instances []InstanceResponse `json:"instances,omitempty"`

	// <p>The relationships between various instances.<p>Valid values:<ul><li>same_node: The specified instances are created on the same physical server. This is useful if you want to ensure low latency across instances.</li><li>different_node: The specified instances aren't created on the same physical server. This is useful if you want to isolate instances for security or redundancy.</li></ul>
	Relationships []map[string]interface{} `json:"relationships,omitempty"`
}
