/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the machine image that you want to create. 
type MachineImagePostRequest struct {

	// Two-part name of the account (<code>/Compute-<em>identity_domain</em>/cloud_storage</code> that contains the credentials and access details of the associated Oracle Storage Cloud Service instance.
	Account string `json:"account"`

	// <p>An optional JSON object or dictionary of arbitrary attributes to be made available to the instance. These are user-defined tags. After defining attributes, you can view them from within an instance at http://192.0.0.192/. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=cloud&id=STCSG-GUID-79AE6910-E6E3-4960-A9A7-368E26D894F6\">Retrieving User-Defined Instance Attributes</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>.
	Attributes map[string]interface{} `json:"attributes,omitempty"`

	// Arbitrary text describing the image.
	Description string `json:"description,omitempty"`

	// <code><em>image_file</em>.tar.gz</code>, where <code><em>image_file</em></code> is the .tar.gz name of the machine image file that you have uploaded to Oracle Storage Cloud Service. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-799D6F6D-BDED-4DDE-9B3D-BE23BE5F687F\">Uploading Machine Image Files to Oracle Storage Cloud Service</a> in <em>Using Oracle Compute Cloud Service (IaaS)</em>.
	File string `json:"file,omitempty"`

	// <p>The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive.
	Name string `json:"name"`

	// <p>Set this to <code>true</code>. Indicates that the image file is available in Oracle Cloud Storage Service.
	NoUpload bool `json:"no_upload,omitempty"`
}
