/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the orchestrationV2 that you want to create. 
type OrchestrationV2PostRequest struct {

	// <code>/Compute-<em>identity_domain</em>/default</code>
	Account string `json:"account,omitempty"`

	// Description of this orchestration
	Description string `json:"description,omitempty"`

	// Specify the desired state of this orchestration: <code>active</code>, <code>inactive</code>, or <code>suspend</code>. You can manage the state of the orchestration objects by changing the desired state of the orchestration.<p>* <code>active</code>: Creates all the orchestration objects defined in the orchestration.<p>* <code>inactive</code>: Adds the orchestration to Oracle Compute Cloud Service, but does not create any of the orchestration objects defined in the orchestration.
	DesiredState string `json:"desired_state"`

	// The three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) of the orchestration.
	Name string `json:"name"`

	// The list of objects in the orchestration. An object is the primary building block of an orchestration. An orchestration can contain up to 100 objects.
	Objects []OrchestrationObjectPostRequest `json:"objects"`

	// Strings that describe the orchestration and help you identify it.
	Tags []string `json:"tags,omitempty"`

	// Version of this orchestration. It is automatically generated by the server.
	Version int32 `json:"version,omitempty"`
}
