/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type OrchestrationV2Response struct {

	// The default Oracle Compute Cloud Service account, such as /Compute-acme/default.
	Account string `json:"account,omitempty"`

	// Description of this orchestration
	Description string `json:"description,omitempty"`

	// The <code>desired_state</code> specified in the orchestration JSON file. A unique identifier for this orchestration.
	DesiredState string `json:"desired_state,omitempty"`

	// Unique identifier of this orchestration
	Id string `json:"id,omitempty"`

	// The three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) of the orchestration.
	Name string `json:"name,omitempty"`

	// List of orchestration objects
	Objects []OrchestrationObjectResponse `json:"objects,omitempty"`

	// Current status of this orchestration
	Status string `json:"status,omitempty"`

	// Strings that describe the orchestration and help you identify it.
	Tags []string `json:"tags,omitempty"`

	// Time the orchestration was last audited
	TimeAudited string `json:"time_audited,omitempty"`

	// The time when the orchestration was added to Oracle Compute Cloud Service.
	TimeCreated string `json:"time_created,omitempty"`

	// The time when the orchestration was last updated in Oracle Compute Cloud Service.
	TimeUpdated string `json:"time_updated,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`

	// Name of the user who added this orchestration or made the most recent update to this orchestration.
	User string `json:"user,omitempty"`

	// Version of this orchestration. It is automatically generated by the server.
	Version int32 `json:"version,omitempty"`
}
