/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type OssContainerResponse struct {

	// The two-part name of the account (<code>/Compute-<i>identity_domain</i>/cloud_storage</code>) that contains the credentials and access details of the associated Oracle Storage Cloud Service instance.
	Account string `json:"account,omitempty"`

	// The name of the container.
	Container string `json:"container,omitempty"`

	// Provides the time when the OSS container was created.
	CreationTime string `json:"creation_time,omitempty"`

	// When set to <code>true</code>, deletes the Oracle Storage Cloud Service container along with all the objects in the container when you delete the integration/osscontainer object created by this orchestration. When set to <code>false</code>, only the integrations/osscontainer object created by this orchestration is deleted. By default, this option is set to <code>true</code>.
	DeleteRemote bool `json:"delete_remote,omitempty"`

	// If delete operation is being carried out, this attribute indicates the current progress of the delete operation. Ignore this attribute value for other operations.
	DeletionProgress string `json:"deletion_progress,omitempty"`

	// Describes the cause for the OSS container object to go into error state.
	ErrorReason string `json:"error_reason,omitempty"`

	// Details applying to the georeplication policy
	GeoreplicationDetails map[string]interface{} `json:"georeplication_details,omitempty"`

	// Optional georeplication policy string
	GeoreplicationPolicy string `json:"georeplication_policy,omitempty"`

	// Time when the OSS container object was last updated.
	ModificationTime string `json:"modification_time,omitempty"`

	// Multipart name of the object.
	Name string `json:"name,omitempty"`

	// Current state of the OSS container object. If the object is in the <code>error</code> state, look at <code>error_reason</code> to identify the cause of this error.
	State string `json:"state,omitempty"`

	// Uniform Resource Identifier.
	Uri string `json:"uri,omitempty"`
}
