/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the private gateway that you want to update. 
type PrivateGatewayPutRequest struct {

	// Description of the object.
	Description string `json:"description,omitempty"`

	// List of IP networks that you want associate with the private gateway. If you are updating a private gateway that is being used in Oracle Network Cloud Service - FastConnect private peering, then traffic starts flowing immediately to instances on the updated IP networks from your premises.
	IpNetworks []string `json:"ipNetworks,omitempty"`

	// The three-part name of the private gateway (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).
	Name string `json:"name"`

	// Tags associated with the object.
	Tags []string `json:"tags,omitempty"`
}
