/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PrivateGatewayResponse struct {

	// Description of the object.
	Description string `json:"description,omitempty"`

	// List of IP networks that is associated with the private gateway. When you set up Oracle Network Cloud Service - FastConnect private peering, you can directly access the instances on these IP networks from your premises without using NAT or IPSec VPN.
	IpNetworks []string `json:"ipNetworks,omitempty"`

	// The three-part name of the private gateway (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).
	Name string `json:"name,omitempty"`

	// Tags associated with the object.
	Tags []string `json:"tags,omitempty"`

	// Uniform Resource Identifier.
	Uri string `json:"uri,omitempty"`
}
