/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the reboot instance request that you want to create. 
type RebootInstanceRequestPostRequest struct {

	// If the instance hangs after it starts running, set this to <code>true</code> to perform a hard reset.
	Hard bool `json:"hard,omitempty"`

	// Multipart name of the instance that you want to reboot.
	Instance string `json:"instance"`
}
