/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RebootInstanceRequestResponse struct {

	// Timestamp of request creation.
	CreationTime string `json:"creation_time,omitempty"`

	// A description of the reason this request entered <code>error</code> state.
	ErrorReason string `json:"error_reason,omitempty"`

	// Perform a hard reset
	Hard bool `json:"hard,omitempty"`

	// Multipart name of the instance that you want to reboot.
	Instance string `json:"instance,omitempty"`

	// Unique identifier generated by the server.
	Name string `json:"name,omitempty"`

	// The state of the request.
	State string `json:"state,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`
}
