/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type RestoreInput struct {

	// Description of the Restore
	Description string `json:"description,omitempty"`

	// The entire URI of the storage volume that should be created when the backup is restored. Ensure that another volume with the same URI does not exist.
	VolumeUri string `json:"volumeUri"`

	// The multi-part name of the object. Object names can contain only alphanumeric characters, hyphens, underscores, @ and periods. Object names are case-sensitive.
	Name string `json:"name,omitempty"`

	// Multi-part name of the backup that you want to restore. The backup must be in the <code>completed</code> state.
	BackupName string `json:"backupName"`
}
