/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SecurityProtocolResponse struct {

	// Description of the object.
	Description string `json:"description,omitempty"`

	// List of port numbers or port range strings to match the packet's destination port.
	DstPortSet []string `json:"dstPortSet,omitempty"`

	// Protocol used in the data portion of the IP datagram.
	IpProtocol string `json:"ipProtocol,omitempty"`

	// Name of the security protocol.
	Name string `json:"name,omitempty"`

	// List of port numbers or port range strings to match the packet's source port.
	SrcPortSet []string `json:"srcPortSet,omitempty"`

	// Tags associated with the object.
	Tags []string `json:"tags,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`
}
