/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SecurityRuleResponse struct {

	// Name of the ACL that contains this rule.
	Acl string `json:"acl,omitempty"`

	// Description of the object.
	Description string `json:"description,omitempty"`

	// List of IP address prefix set names to match the packet's destination IP address.
	DstIpAddressPrefixSets []string `json:"dstIpAddressPrefixSets,omitempty"`

	// Name of virtual NIC set containing the packet's destination virtual NIC.
	DstVnicSet string `json:"dstVnicSet,omitempty"`

	// Allows the security rule to be disabled.
	EnabledFlag bool `json:"enabledFlag,omitempty"`

	// Direction of the flow; Can be \"egress\" or \"ingress\".
	FlowDirection string `json:"flowDirection,omitempty"`

	// Name of the security rule.
	Name string `json:"name,omitempty"`

	// List of security protocol object names to match the packet's protocol and port.
	SecProtocols []string `json:"secProtocols,omitempty"`

	// List of multipart names of IP address prefix set to match the packet's source IP address.
	SrcIpAddressPrefixSets []string `json:"srcIpAddressPrefixSets,omitempty"`

	// Name of virtual NIC set containing the packet's source virtual NIC.
	SrcVnicSet string `json:"srcVnicSet,omitempty"`

	// Tags associated with the object.
	Tags []string `json:"tags,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`
}
