/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SnapshotResponse struct {

	// Shows the default account for your identity domain.
	Account string `json:"account,omitempty"`

	// Timestamp when this request was created.
	CreationTime string `json:"creation_time,omitempty"`

	// Snapshot of the instance is not taken immediately.
	Delay string `json:"delay,omitempty"`

	// A description of the reason this request entered \"error\" state.
	ErrorReason string `json:"error_reason,omitempty"`

	// Multipart name of the instance.
	Instance string `json:"instance,omitempty"`

	// Three-part name of the machine image generated from the instance snapshot request.
	Machineimage string `json:"machineimage,omitempty"`

	// Multipart name of the instance snapshot request.
	Name string `json:"name,omitempty"`

	// Not used
	Quota string `json:"quota,omitempty"`

	// The state of the request.
	State string `json:"state,omitempty"`

	// Uniform Resource Identifier
	Uri string `json:"uri,omitempty"`
}
