/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the SSH key that you want to update. 
type SshKeyPutRequest struct {

	// <p>Indicates whether the key must be enabled (default) or disabled. Note that disabled keys cannot be associated with instances.<p>To explicitly enable the key, specify <code>true</code>. To disable the key, specify <code>false</code>.
	Enabled bool `json:"enabled,omitempty"`

	// <p>The SSH public key value.
	Key string `json:"key"`

	// <p>The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).
	Name string `json:"name"`
}
