/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the storage volume that you want to update. 
type StorageVolumePutRequest struct {

	// <p>The description of the storage volume.
	Description string `json:"description,omitempty"`

	// The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>).
	Name string `json:"name"`

	// <p>The storage-pool property.<p>For storage volumes that require low latency and high IOPS, such as for storing database files, specify <code>/oracle/public/storage/latency</code>.<p>For all other storage volumes, specify <code>/oracle/public/storage/default</code>.
	Properties []string `json:"properties"`

	// <p>The size of this storage volume. Use one of the following abbreviations for the unit of measurement:<ul><li><code>B</code> or <code>b</code> for bytes</li><li><code>K</code> or <code>k</code> for kilobytes</li><li><code>M</code> or <code>m</code> for megabytes</li><li><code>G</code> or <code>g</code> for gigabytes</li><li><code>T</code> or <code>t</code> for terabytes</li></ul><p>For example, to create a volume of size 10 gigabytes, you can specify <code>10G</code>, or <code>10240M</code>, or <code>10485760K</code>, and so on.<p>The allowed range is from 1 GB to 2 TB, in increments of 1 GB.
	Size string `json:"size"`

	// <p>Strings that you can use to tag the storage volume.
	Tags []string `json:"tags,omitempty"`
}
