/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the storage attachment that you want to create. 
type StorageAttachmentPostRequest struct {

	// <p>Index number for the volume. The allowed range is 1-10. The index determines the device name by which the volume is exposed to the instance. Index 0 is allocated to the temporary boot disk, /dev/xvda An attachment with index 1 is exposed to the instance as /dev/xvdb, an attachment with index 2 is exposed as /dev/xvdc, and so on.
	Index int32 `json:"index"`

	// Multipart name of the instance to which you want to attach the volume.
	InstanceName string `json:"instance_name"`

	// <p>Three part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object_name</em></code>) of the volume that you want to attach.<p>For information about how to create a storage volume, see <a class=\"xref\" href=\"op-storage-volume--post.html\">Create a Storage Volume</a>.
	StorageVolumeName string `json:"storage_volume_name"`
}
