/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the VPN endpoint v2 that you want to update. 
type VpnConnectionPutRequest struct {

	// Specify the IP address of the VPN gateway in your data center through which you want to connect to the Oracle Cloud VPN gateway. Your gateway device must support policy-based VPN and IKE (Internet Key Exchange) configuration using pre-shared keys.
	CustomerVpnGateway string `json:"customer_vpn_gateway"`

	// The Internet Key Exchange (IKE) ID. If you don't specify a value, the default value is the public IP address of the cloud gateway. You can specify either an alternative IP address, or any text string that you want to use as the IKE ID. If you specify a text string, you must prefix the string with @. For example, if you want to specify the text IKEID-for-VPN1, specify <code>@IKEID-for-VPN1</code> as the value in request body. If you specify an IP address, don't prefix it with @. The IKE ID is case sensitive and can contain a maximum of 255 ASCII alphanumeric characters including special characters, period (.), hyphen (-), and underscore (_). The IKE ID can't contain embedded space characters.<p><b>Note:</b> If you specify the IKE ID, ensure that you specify the Peer ID type as Domain Name on the third-party device in your data center. Other Peer ID types, such as email address, firewall identifier or key identifier, aren't supported.
	IkeIdentifier string `json:"ikeIdentifier,omitempty"`

	// Specify the three-part name of the IP network (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) in which you want to create the cloud gateway. When you send a request to create a VPN connection, a cloud gateway is created and this is assigned an available IP address from the IP network that you specify. So, the cloud gateway is directly connected to the IP network that you specify.<p>You can only specify a single IP network. All other IP networks which are connected to the specified IP network through an IP network exchange are discovered and added automatically to the VPN connection.
	IpNetwork string `json:"ipNetwork"`

	// The three-part name (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>) of the VPN connection. Object names can contain only alphanumeric, underscore (_), dash (-), and period (.) characters. Object names are case-sensitive.
	Name string `json:"name"`

	// This is enabled (set to <code>true</code>) by default. If your third-party device supports Perfect Forward Secrecy (PFS), set this parameter to <code>true</code> to require PFS. 
	PfsFlag bool `json:"pfsFlag,omitempty"`

	// Settings for Phase 1 of protocol (IKE). See below for object members.<p> phase1Settings.encryption: Encryption options for IKE. Possible values are <code>aes128</code>, <code>aes192</code>, <code>aes256</code>. Default is combination of all possible values. <p> phase1Settings.hash: Authentication options for IKE. Possible values are <code>sha1</code>, <code>sha2_256</code>, <code>md5</code>. Default is combination of all possible values. <p> phase1Settings.dhGroup: Diffie-Hellman group for both IKE and ESP. It is applicable for ESP only if PFS is enabled. Possible values are <code>group2</code>, <code>group5</code>, <code>group14</code>, <code>group22</code>, <code>group23</code>, <code>group24</code>. Default is combination of all possible values
	Phase1Settings map[string]interface{} `json:"phase1Settings,omitempty"`

	// Settings for Phase 2 of protocol (IPSEC).See below for object members.<p>phase2Settings.encryption: Encryption options for IKE. Possible values are <code>aes128</code>, <code>aes192</code>, <code>aes256</code>. Default is combination of all possible values. <p> phase2Settings.hash: Authentication options for IKE. Possible values are <code>sha1</code>, <code>sha2_256</code>, <code>md5</code>. Default is combination of all possible values.
	Phase2Settings map[string]interface{} `json:"phase2Settings,omitempty"`

	// Pre-shared VPN key. Enter the pre-shared key. This secret key is shared between your network gateway and the Oracle Cloud network for authentication. Specify the full path and name of the text file that contains the pre-shared key. Ensure that the permission level of the text file is set to 400. The pre-shared VPN key must not exceed 256 characters.
	Psk string `json:"psk"`

	// Specify a list of customer subnets (CIDR prefixes) that are reachable through this VPN tunnel. You can specify a maximum of 20 IP subnet addresses. Specify IPv4 addresses in dot-decimal notation with or without mask.
	ReachableRoutes []string `json:"reachable_routes"`

	// Comma-separated list of vNIC sets. Traffic is allowed to and from these vNIC sets to the cloud gateway's vNIC set.
	VnicSets []string `json:"vnicSets,omitempty"`
}
