/* 
 * REST API for Oracle Cloud Infrastructure Compute Classic
 *
 * Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources. <p>All documentation is applicable to using the API on Oracle Cloud and Oracle Cloud Machine, unless otherwise indicated.
 *
 * OpenAPI spec version: 2017.09.21
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The request body contains details of the VPN endpoint that you want to create. 
type VpnEndpointPostRequest struct {

	// Specify the IP address of the VPN gateway in your data center through which you want to connect to the Oracle Cloud VPN gateway. Your gateway device must support policy-based VPN and IKE (Internet Key Exchange) configuration using pre-shared keys.
	CustomerVpnGateway string `json:"customer_vpn_gateway"`

	// Enables the VPN endpoint. To start a VPN connection, set to <code>true</code>. A connection is established immediately, if possible. If you do not specify this option, the VPN endpoint is disabled and the connection is not established.
	Enabled bool `json:"enabled,omitempty"`

	// Three-part name of the object (<code><em>/Compute-acme/object</em></code>).Object names can contain only alphanumeric, underscore (_), dash (-), and period (.) characters. Object names are case-sensitive.
	Name string `json:"name"`

	// Pre-shared VPN key. Enter the pre-shared key. This must be the same key that you provided when you requested the service. This secret key is shared between your network gateway and the Oracle Cloud network for authentication. Specify the full path and name of the text file that contains the pre-shared key. Ensure that the permission level of the text file is set to 400. The pre-shared VPN key must not exceed 256 characters.
	Psk string `json:"psk"`

	// Specify a list of customers subnets (CIDR prefixes) that are reachable through this VPN tunnel. You can specify a maximum of 20 IP subnet addresses. Specify IPv4 addresses in dot-decimal notation with or without mask.
	ReachableRoutes []string `json:"reachable_routes"`
}
